### ISSUE TITLE
Link the Discord in the community page?

### ISSUE THREAD

**Issue by Fancy2209** [airsdk/airsdk.dev#102]
Even if company policies don't allow Harman employees to be there, it's still a community place, so I think it should be added to 
https://airsdk.dev/community

Invite 
https://discord.gg/kBSPUkevVt

**Comment by marchbold** [comment]
Considering up until a few days ago there was only 2 people in the discord server I hadn't considered it a space AIR developers used. 

I'll monitor the server and add it as part of the next update.

**Comment by marchbold** [comment]
Live now
