### ISSUE TITLE
where can I download AirSDK old version. 

### ISSUE THREAD

**Issue by code5381** [airsdk/airsdk.dev#12]
Hello,

I'm looking for Adobe AIR SDK old version, but the link page was closed. (Only 32.0 version is opened .)

http://airdownload.adobe.com/air/win/download/32.0/AdobeAIRSDK.zip (O)
http://airdownload.adobe.com/air/win/download/22.0/AdobeAIRSDK.zip (X)

I've googled for 2 days. There is no way to find a old version.

Please let me know how to get it. You can be my hero. :)

Thanks in advanced.

Kevin.

**Comment by marchbold** [comment]
Probably a better question for the AIR discussion forum:

https://github.com/airsdk/Adobe-Runtime-Support/discussions

We don't have a license from Adobe to distribute old versions through this site.
