### ISSUE TITLE
Typo in docs/building/application-descriptor-files/elements/android

### ISSUE THREAD

**Issue by jigtrap** [airsdk/airsdk.dev#127]
Sorry it this kind of issue is not usual.

I am almost sure that it should says "help prevent ANR issues", instead of "help prevent  ANE issues"
Link:
https://airsdk.dev/docs/building/application-descriptor-files/elements/android
Element: runtimeInBackgroundThread

//--------------------
runtimeInBackgroundThread
(optional)

Available: 50.2.1.1

If true, this causes the AIR runtime to be launched in a separate, background thread rather than in the main Android UI thread. This should help prevent ANE issues, but may require some updates in other Android Java code (i.e. from AIR Native Extensions that may need some of their code to run on the UI thread). Default is false.

**Comment by marchbold** [comment]
ANR is correct, it stands for Application Not Responding and can be caused when there is a large operation done on the main thread. Running AIR in the background thread can help alleviate these issues.

**Comment by jigtrap** [comment]
> ANR is correct, it stands for Application Not Responding and can be caused when there is a large operation done on the main thread. Running AIR in the background thread can help alleviate these issues.

I thought so, it needs to be corrected in the docs.
https://airsdk.dev/docs/building/application-descriptor-files/elements/android

Thanks in advance.
